### ISSUE TITLE
Letter key input doesn't work on wayland. 

### ISSUE THREAD

**Issue by dwestford17** [flathub/com.github.tmewett.BrogueCE#8]
When on wayland, the letter keys on the keyboard do not work. I can move with the arrow keys but all other actions tied to the letter keys on the keyboard do not work. When switched to an xorg session, there are no issues. No issues with mouse input on either. 

OS: Fedora 36 (issue also present on Fedora 35)
DE: Gnome Wayland Session

**Comment by tmewett** [comment]
Brogue uses a [hybrid text input system](https://github.com/tmewett/BrogueCE/blob/v1.10.1/src/platform/sdl2-platform.c#L186) where character-producing keys are read by the SDL text input system, and the others are read by the keyboard system. This explains why only some work, but not why the text input part isn't working. Do you know if it works outside of Flatpak? (There are binaries on the CE release page)

**Comment by dwestford17** [comment]
Forgot to mention that. The official releases from the BrogeCE git page work fine. This only affects the flatpak version. The flatpak version of DCSS also shares the same issue.

**Comment by arteymix** [comment]
For reference, here's the issue for Crawl: https://github.com/flathub/org.develz.Crawl/issues/15

Crawl uses SDL for its text input too.

**Comment by jtmusky** [comment]
Can confirm on RHEL9 using Gnome wayland; same issue. Some keys don't work.

**Comment by huanie** [comment]
A workaround would be to disable wayland and force x11 with Flatseal.
For the maintainers, it would be removing ``--socket=wayland`` in <https://github.com/flathub/com.github.tmewett.BrogueCE/blob/master/com.github.tmewett.BrogueCE.json>

**Comment by 239** [comment]
Works for me after the update :+1:

**Comment by mckibble** [comment]
Was trying to build a 1.13 flatpak and was getting the same issue about letter keys not working. The above workarounds did not work for me. To clarify, I am running Brogue on a Steam Deck, which uses Wayland.

Changing the runtime to freedesktop 22.08 (i.e. the old version) did the trick.

Might have something to do with SDL updating how they detect keyboards:
 https://github.com/libsdl-org/SDL/issues/8561

**Comment by mserajnik** [comment]
The issue should be fixed in the latest update (by reverting the Freedesktop runtime from 23.08 to 22.08).

Can someone who was affected here confirm this?

Ideally, we would update the runtime to 24.08 since 22.08 is EOL; see #21.
Maybe someone affected could also [install the test build from that PR](https://github.com/flathub/com.github.tmewett.BrogueCE/pull/21#issuecomment-2498083858) and confirm if it's still working with Freedesktop runtime version 24.08 too?

**Comment by dwestford17** [comment]
I can confirm that with the latest update the keyboard letter keys work again. 

Just checked the test build. Works there too. 

I'll leave the issue open for others to test in the mean time but it all looks good on my end.

**Comment by mserajnik** [comment]
@dwestford17 Thank you for the feedback!

I was also able to confirm that this issue isn't present with Freedesktop runtime 24.08 on the Steam Deck (which uses an embedded Gamescope session), where there [have been reports on Reddit](https://www.reddit.com/r/brogueforum/comments/yco8h6/comment/lqwtck6/) that it is affected by this too.

Combined with your confirmation that it also works on Gnome, I think that it should be safe to update. I have therefore removed the draft state from #21 accordingly and marked it so that it will close this issue once it gets merged.

**Comment by tmewett** [comment]
Thanks everyone for your work in diagnosing and solving this!
